configs = {
    'b':
    {
    'scalp': 1,
    'embed_dim': 112,
    'num_heads': 2,
    'stages': (2, 3, 16, 3),
    'global_att_blocks': (12,16,20),
    'window_pos_embed_bkg_spatial_size': [14, 14],
    'window_spec': [8, 4, 14, 7],
    'num_pos_feats': 256,
    'normalize': True,
    'scale': None,
    'temperature': 10000,
    'd_model': 256,
    'backbone_channel_list': [896, 448, 224, 112],
    'fpn_top_down_levels': [2, 3],
    'fpn_interp_model': 'nearest',
    },

    'l': 
    {
    'scalp': 0,
    'embed_dim': 144,
    'num_heads': 2,
    'stages': (2, 6, 36, 4),
    'global_att_blocks': (23, 33, 43),
    'window_pos_embed_bkg_spatial_size': [7, 7],
    'window_spec': [8, 4, 16, 8],
    'num_pos_feats': 256,
    'normalize': True,
    'scale': None,
    'temperature': 10000,
    'd_model': 256,
    'backbone_channel_list': [1152, 576, 288, 144],
    'fpn_top_down_levels': [2, 3],
    'fpn_interp_model': 'nearest',
    },

    's':
    {
    'scalp': 0,
    'embed_dim': 96,
    'num_heads': 1,
    'stages': (1, 2, 11, 2),
    'global_att_blocks': (7, 10, 13),
    'window_pos_embed_bkg_spatial_size': [7, 7],
    'window_spec': [8, 4, 14, 7],
    'num_pos_feats': 256,
    'normalize': True,
    'scale': None,
    'temperature': 10000,
    'd_model': 256,
    'backbone_channel_list': [768, 384, 192, 96],
    'fpn_top_down_levels': [2, 3],
    'fpn_interp_model': 'nearest',
    },

    't':
    {
    'scalp': 0,
    'embed_dim': 96,
    'num_heads': 1,
    'stages': (1, 2, 7, 2),
    'global_att_blocks': (5, 7, 9),
    'window_pos_embed_bkg_spatial_size': [7, 7],
    'window_spec': [8, 4, 14, 7],
    'num_pos_feats': 256,
    'normalize': True,
    'scale': None,
    'temperature': 10000,
    'd_model': 256,
    'backbone_channel_list': [768, 384, 192, 96],
    'fpn_top_down_levels': [2, 3],
    'fpn_interp_model': 'nearest',
    }, 
}